import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/components/Navbar'
import { getApiLimitCredits } from '@/lib/apiLimit'
import { ProTextProvider } from '@/components/pro-text-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({
  children,
}: {
  children: React.ReactNode
}) => {

  const apiLimitCredits = await getApiLimitCredits();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar apiLimitCredits={apiLimitCredits}/>
            <ProTextProvider />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}

export default RootLayout;
